### ISSUE TITLE
No file named relation_description.txt

### ISSUE THREAD

**Issue by DukeXU-philips** [Ac-Zyx/RoCORE#5]
Hi,

I'm trying to run the code, but it seems it needs to pre-define a relation_description.txt file which is not mentioned in README. Could you please help to solve it ? thanks in advance

**Comment by Skytliang** [comment]
Have you solved this problem?

**Comment by DukeXU-philips** [comment]
> Have you solved this problem?

Sorry for late response. It is still unsolved. It will be appreciated if you can help with it. Thanks in advance.

**Comment by Ac-Zyx** [comment]
Sorry for the late reply，we have updated it now.
